name: Build
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
        qt: [5.15.2]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ runner.arch }}
          max-size: 100M

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1  # not v2! TODO: why though?
        with:
          path: ../Qt
          key: ${{ matrix.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.22.x'

      - name: Build
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          mkdir -p build install
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=install
          make -C build -j$(nproc) install

      - uses: actions/upload-artifact@v2
        with:
          name: portable-binary.${{ github.sha }}.${{ matrix.os }}-${{ runner.arch }}
          path: install/**
