name: Check Formatting

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  checks:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Format
        run: .ci/format.sh

      - name: Check diff
        run: git --no-pager diff --exit-code HEAD