name: Metainfo-updater

on:
  push:
    tags:
      - "*"

jobs:
  xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Update metainfo with tag-metainfo-xml
        run: |
          git clone https://github.com/dada513/tag-metainfo-xml metainfo-updater
          cd metainfo-updater
          git checkout 684da34f49fc3f119d15751049556b51612a24e7
          go build
          ./tag-metainfo-xml PolyMC PolyMC ../program_info/org.polymc.PolyMC.metainfo.xml
      - name: update tag with metainfo changes
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git add program_info/org.polymc.PolyMC.metainfo.xml
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          msg=$(git tag -l --format='%(contents)' $tag)
          git commit -m "$msg"
          git tag -f $tag
          git push --force origin $tag
