name: Metainfo-updater

on:
  push:
    tags:
      - "*"

jobs:
  xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Update metainfo with tag-metainfo-xml
        run: |
          git clone https://github.com/dada513/tag-metainfo-xml metainfo-updater
          cd metainfo-updater
          git checkout ace02c74fe014def09250c161c87d82cecd95036
          go build
          ./tag-metainfo-xml PolyMC PolyMC ../program_info/org.polymc.PolyMC.metainfo.xml
      - name: update tag with metainfo changes
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add program_info/org.polymc.PolyMC.metainfo.xml
          git commit -m "bot: update metainfo with latest tags"
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          git tag -f $tag
          git push --force origin $tag
