name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release
    secrets:
      SPARKLE_ED25519_KEY: ${{ secrets.SPARKLE_ED25519_KEY }}

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          path: 'PolyMC-source'
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/PolyMC-source PolyMC-${{ env.VERSION }}
          mv PolyMC-Linux-Qt6-Portable*/PolyMC-portable.tar.gz PolyMC-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv PolyMC-Linux-Qt6*/PolyMC.tar.gz PolyMC-Linux-Qt6-${{ env.VERSION }}.tar.gz          
          mv PolyMC-Linux-Portable*/PolyMC-portable.tar.gz PolyMC-Linux-Portable-${{ env.VERSION }}.tar.gz
          mv PolyMC-Linux*/PolyMC.tar.gz PolyMC-Linux-${{ env.VERSION }}.tar.gz
          mv PolyMC-*.AppImage/PolyMC-*.AppImage PolyMC-Linux-${{ env.VERSION }}-x86_64.AppImage
          mv PolyMC-macOS*/PolyMC.tar.gz PolyMC-macOS-${{ env.VERSION }}.tar.gz

          tar -czf PolyMC-${{ env.VERSION }}.tar.gz PolyMC-${{ env.VERSION }}

          for d in PolyMC-Windows-*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="PolyMC-Windows"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv PolyMC-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: PolyMC ${{ env.VERSION }}
          draft: true
          prerelease: false
          files: |
            PolyMC-Linux-${{ env.VERSION }}.tar.gz
            PolyMC-Linux-Portable-${{ env.VERSION }}.tar.gz
            PolyMC-Linux-${{ env.VERSION }}-x86_64.AppImage
            PolyMC-Windows-Legacy-${{ env.VERSION }}.zip
            PolyMC-Linux-Qt6-${{ env.VERSION }}.tar.gz
            PolyMC-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            PolyMC-Windows-Legacy-Portable-${{ env.VERSION }}.zip
            PolyMC-Windows-Legacy-Setup-${{ env.VERSION }}.exe
            PolyMC-Windows-${{ env.VERSION }}.zip
            PolyMC-Windows-Portable-${{ env.VERSION }}.zip
            PolyMC-Windows-Setup-${{ env.VERSION }}.exe
            PolyMC-macOS-${{ env.VERSION }}.tar.gz
            PolyMC-${{ env.VERSION }}.tar.gz
