name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release
      version: ${{ github.ref_name }}
    secrets:
      SPARKLE_ED25519_KEY: ${{ secrets.SPARKLE_ED25519_KEY }}

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
          path: 'PolyMC-source'

      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Grab and store version
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Package artifacts properly
        run: ./.ci/pack.sh

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: PolyMC ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: dist/*
