name: Build Application

on:
  push:
    branches-ignore:
      - 'stable'
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - '**.nix'
      - 'packages/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.markdownlint**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - '**.nix'
      - 'packages/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.markdownlint**'
  workflow_dispatch:

jobs:
  build_debug:
    name: Build Debug
    uses: ./.github/workflows/build.yml
    with:
      build_type: Debug
    secrets:
      SPARKLE_ED25519_KEY: ${{ secrets.SPARKLE_ED25519_KEY }}

  test_release:
    needs: build_debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
          path: 'PolyMC-source'

      - name: Grab and store version
        run: echo "VERSION=$(git rev-parse --short=10 HEAD)" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Package artifacts properly
        run: ./.ci/pack.sh
